name: pymc3
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - arviz=0.12.0
  - bottleneck=1.3.4
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=5.0.0
  - cftime=1.6.0
  - curl=7.82.0
  - dill=0.3.4
  - fastprogress=1.0.2
  - filelock=3.6.0
  - freetype=2.10.4
  - hdf4=4.2.15
  - hdf5=1.12.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - jpeg=9e
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libssh2=1.10.0
  - libzip=1.8.0
  - llvm-openmp=13.0.1
  - matplotlib-base=3.2.2
  - mkl=2022.0.0
  - mkl-service=2.4.0
  - ncurses=6.3
  - netcdf4=1.5.8
  - numexpr=2.8.0
  - openssl=1.1.1n
  - patsy=0.5.2
  - pip=21.2.2
  - python=3.7.13
  - python-dateutil=2.8.2
  - python_abi=3.7
  - readline=8.1.2
  - scipy=1.7.3
  - semver=2.13.0
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - tbb=2021.5.0
  - theano-pymc=1.1.2
  - tk=8.6.11
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - wheel=0.37.1
  - xarray=0.20.2
  - xz=5.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - pip:
    - aesara-theano-fallback==0.1.0
    - appnope==0.1.3
    - argon2-cffi==20.1.0
    - argon2-cffi-bindings==21.2.0
    - asteval==0.9.26
    - astroalign==2.4.1
    - astropy==4.3.1
    - astroquery==0.4.6
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - barycorrpy==0.4.4
    - beautifulsoup4==4.11.1
    - bleach==3.3.1
    - bokeh==2.4.2
    - certifi==2020.12.5
    - cffi==1.14.6
    - chardet==4.0.0
    - charset-normalizer==2.0.12
    - colorcet==3.0.0
    - corner==2.2.1
    - cycler==0.10.0
    - cython==0.29.28
    - debugpy==1.6.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - deprecat==2.1.1
    - elca==1.0.0
    - emcee==3.1.1
    - entrypoints==0.4
    - exoplanet==0.5.2
    - exoplanet-core==0.1.2
    - exotic==1.10.1
    - fastjsonschema==2.15.3
    - fonttools==4.33.3
    - future==0.18.2
    - holoviews==1.14.9
    - html5lib==1.1
    - idna==2.10
    - imageio==2.19.2
    - importlib-resources==5.7.1
    - ipykernel==5.5.6
    - ipython==7.23.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jplephem==2.17
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.13
    - jupyter-console==6.4.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - keyring==23.5.0
    - ldtk==1.7.0
    - llvmlite==0.38.0
    - lmfit==1.0.3
    - markdown==3.3.7
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - memory-profiler==0.60.0
    - mistune==0.8.4
    - nbclient==0.5.13
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.5
    - networkx==2.6.3
    - notebook==6.3.0
    - numba==0.55.1
    - numpy==1.21.6
    - ortools==8.0.8283
    - packaging==21.3
    - pandas==1.2.5
    - pandocfilters==1.4.3
    - panel==0.13.0
    - param==1.12.1
    - parso==0.8.3
    - pexpect==4.8.0
    - photutils==1.3.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - prometheus-client==0.10.1
    - prompt-toolkit==3.0.29
    - protobuf==3.13.0
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pycparser==2.21
    - pyct==0.4.8
    - pyerfa==2.0.0.1
    - pygments==2.9.0
    - pylightcurve==4.0.1
    - pymc3==3.11.5
    - pymc3-ext==0.1.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-version==0.0.2
    - pytz==2021.3
    - pyviz-comms==2.2.0
    - pyvo==1.2.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==22.0.3
    - qtconsole==5.1.1
    - qtpy==1.9.0
    - requests==2.27.1
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - semantic-version==2.9.0
    - send2trash==1.5.0
    - sep==1.2.0
    - setuptools-scm==6.4.2
    - soupsieve==2.3.2.post1
    - starry==1.2.0
    - statsmodels==0.13.2
    - tenacity==8.0.1
    - terminado==0.9.5
    - testpath==0.4.4
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tinycss2==1.1.1
    - tomli==2.0.1
    - tqdm==4.64.0
    - traitlets==5.0.5
    - typing-extensions==4.2.0
    - ultranest==3.3.3
    - uncertainties==3.1.6
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
    - wrapt==1.14.0
